### ISSUE TITLE
Decide on weather to replace the old samplers with the new samplers in the training material and CUQI book

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQI-Book#40]
Description:
------------
An informed decision is needed regarding which sampler module to use in the training, the old or the new experimental one. Charlie and @amal-ghamdi think it is better to use the new sampler module because it shows the flexibility of Gibbs sampling.

Definition of done:
-------------------
- [x] @jakobsj and Nicolai's thoughts on this are obtained and a decision is made
- [x] If the decision is to use the new sampler module, an issue is created to update all the training / mini book material to use the new sampler module. 
- [x] #55
- [x] assign issue Nicolai update BayesainProblem (2 modes legacy and new)

Note:
--------
We had a discussion, and we made the decision to replace the old samplers with new ones in the training materials. @amal-ghamdi will create the remaining issues.

**Comment by jakobsj** [comment]
To help make an informed decision: What are pros and cons of each strategy (keep or switch)? What is a rough time estimate to switch? Which problems or time sinks do you foresee we may run into if implementing the switch?

**Comment by chaozg** [comment]
- I just want to add that only those notebooks related to sampling need to be updated, so

  - Distribution, no need
  - Forward model, no
  - Bayesian inversion, yes
  - Gibbs, yes
  - PDE, yes
  - Plugins (CIL, FEniCS, PyTorch), yes

- For Bayesian inversion and PDE, we only need minor updates 
  1. sampler import:
  ```python
  from cuqi.experimental.mcmc import PCN, MH, CWMH` #if we create alias and remove the -`New`
  ```
  2. generate samples:
  ```python
  MySampler.warmup(500)
  MySampler.sample(1000)
  posterior_samples = MySampler.get_samples()
  ```
  I've run Bayesian inversion and PDE with the above changes and these two notebooks run without any problem.

- For Gibbs, major changes are expected.
- For plugin notebooks, some work is needed to update these plugins first.

**Comment by amal-ghamdi** [comment]
We ha
