### ISSUE TITLE
Book review, by Nicolai

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQI-Book#42]
Description:
-------------
Go over the book material for review and light edits.

Definition of done:
--------------------
- [ ] A light edit of the book is done  
- [ ] The edits PR is reviewed
- [ ] The edits merged in the main incorporating the review comments
- [ ] Issues are created for more substantial edits if needed

**Comment by nabriis** [comment]
Comment from duplicate issue:

Hi @nabriis, it would be great if you can go through the book

Note that:

Chapter 2 includes Gibbs notebook which is almost the same one as in the training (included in Chapter A) but with additional exercises and style update
Chapter A has the basic training material that was in the CUQIpy-Demo repo with a complete git history
Chapter B has the advanced (PDE + plugin) training material that was also in the demo (also with complete git history)
I removed some parts of the book that are not very relevant to the training and parts that are repeated. But this is still a work in progress.
(fyi about the book update notes @jakobsj , @chaozg )
