### ISSUE TITLE
Find solution for the build environment/Jupyter book to enable including CIL/FENICS/PyTorch based code in the book

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQI-Book#44]
Description:
-------------
The CUQI-Book/training material contains code that uses CIL/FEniCS/PyTorch. Find out if it is possible to set up the book compilation environment to render executed notebooks that use these libraries (can we set one environment or maybe multiple, each used for the corresponding notebook). If not possible or feasible, find a workaround solution, for example, adding directives to not execute these notebooks or decide on where to place these notebooks if it is not possible to include them in the CUQI-Book

Definition of done:
-------------------
- [x] A solution or a workaround solution is found
- [x] The solution or the workaround solution is agreed on by CUQIpy team
- [x] The solution or the workaround solution is implemented, reviewed and merged

Notes:
--------
The suggested workaround solution is to ignore the notebooks depending on CIL/FEniCS/PyTorch from execution
- We then can decide if we want them to be executed locally (local machine then pushed to the repo) or remain unexecuted
- An example of how this looks like (if executed locally) is already in the book: https://cuqi-dtu.github.io/CUQI-Book

**Comment by jakobsj** [comment]
I very much like the solution of diplaying the already locally offline executed notebooks with results as part of the book. Perhaps a heads-up should be given somewhere that execution is disabled and so a reader would have to run it elsewhere. Approving.

**Comment by amal-ghamdi** [comment]
thank you @jakobsj for you review. I added the comment about the heads-up to the list of your book comments: #57
