### ISSUE TITLE
Update cuqipy overview section in the book to be used in the training

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQI-Book#53]
Description:
------------
Update the overview about CUQIpy in the book. The goal is to make it generic and suitable for the book. Also, split it into multiple pages as needed.

DoD:
------
- [ ] Overview about CUQIpy in the book is updated (possibility splitted into multiple pages)
- [ ] The updates reviewed by a member of the team other than the assignee, approved and merged.

**Comment by amal-ghamdi** [comment]
@jakobsj Can you review the DoD, please? Thanks.

**Comment by jakobsj** [comment]
I am not completely sure what specifically this issue aims to do.  Could it be that we keep the overview general for the book (not specific to the course) and provide specific information and links in the collaborative note?

**Comment by amal-ghamdi** [comment]
@jakobsj, thanks for the feedback. I splitted the issue into 2 as you suggested. The other one is in CUQIpy-admin. Can you take a look again at this to approve the DoD? and I will tag you in the other one.
Thanks!

**Comment by jakobsj** [comment]
@amal-ghamdi looks good thanks!

**Comment by amal-ghamdi** [comment]
results in test book https://amal-ghamdi.github.io/CUQI-Book-test/intro.html
