### ISSUE TITLE
Use the new sampler module in all the Book material

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQI-Book#54]
Description:
-------------
We made a decision to update the book material to use the new sampler module instead of the old one (the Gibbs notebook has a separate issue #55)

DoD:
------
- [x] The book examples are updated to use the new sampler module instead of the old one (except the Gibbs notebook)
- [x] Results in the book pages are checked against old samplers version and are meaningful.
- [x] Sampling progress printing is checked to look presentable (note: new samplers uses tqdm)
- [ ] The changes are reviewed and merged

Note:
------
- notes from @chaozg in https://github.com/CUQI-DTU/CUQI-Book/issues/40 could be relevant

**Comment by nabriis** [comment]
Can you review DOD @jakobsj

**Comment by jakobsj** [comment]
I think the "correctly" one should be specified / split a tiny bit. For example:

All cells in the book pages run with meaningful output.
Results in the book pages are checked against old samplers version and are meaningful.
Any exercises and suggested solutions are checked and meaningful.

**Comment by amal-ghamdi** [comment]
@jakobsj I added one DoD here, please check it out:
"- [ ] Sampling progress printing is checked to look presentable (note: new samplers use tqdm)"

thanks 

(FYI @nabriis)
