### ISSUE TITLE
Update the Gibbs notebook in the book

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQI-Book#55]
This is related to #54 to replace the old sampler with the new one. Since the Gibbs notebook requires additional care in replacing the old sampler with the new one, we kept it in a separate issue.

DoD:
-------
- [x] The Gibbs notebook in the book is updated to use the new sampler module instead of the old one
- [x] All cells in the notebook run with meaningful output.
- [x] Results in the notebook are checked against old samplers version and are meaningful.
- [x] Any exercises and suggested solutions are checked and meaningful.
- [x] The changes are reviewed and merged

**Comment by nabriis** [comment]
Can you review DOD @jakobsj

**Comment by jakobsj** [comment]
I think the "correctly" one should be specified / split a tiny bit. For example:

All cells in the notebook run with meaningful output.
Results in the notebook are checked against old samplers version and are meaningful.
Any exercises and suggested solutions are checked and meaningful.
