### ISSUE TITLE
Add suggestions from Charlie about the book

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQI-Book#68]
Description:
-------------
Addressing the following comments from Charlie about the book:

**needed now**
- [ ] Note about how to run the book material: " Just a thought: this is a vital piece of information for using this book, and it's a pit that it is somehow hidden in a section called "Overview of CUQIpy". Do you think it deserves a more noticeable place, for example somewhere before chapter01?"
- [ ] fix the word donut (from dount) 

**easy**
- [ ] Add reference to GMRF
- [ ] The file name gradient_based_sampling_with_cuqipy.ipynb is a bit misleading (to ourselves when editing) as this notebook contains more "stories" than just gradient sampling. What do you think?

**could wait**

DoD:
------
- [ ] The above suggestions are addressed
- [ ] The updates are reviewed and merged

**Comment by amal-ghamdi** [comment]
@jakobsj, would you please review the DoD, I organized the comments from @chaozg into three groups. The top group I would like to address today along with #53 in one PR. Also feel free to suggest moving the comments along the sections (needed now, easy, can wait)
Thank you.

**Comment by jakobsj** [comment]
@amal-ghamdi approved
