### ISSUE TITLE
Update forward model notebook if necessary

### ISSUE THREAD

**Issue by chaozg** [CUQI-DTU/CUQI-Book#70]
DoDs:
- [x] update the ToC link to forward UQ so that it at least works within the notebook
- [x] add a link to the specific notebook on geometries
- [x] update links to other notebooks as they are broken due to reconstruction
- [x] minor update if necessary
- [ ] maybe reduce the content on geometries in forward models since there is a specific notebook?

Notes:
@amal-ghamdi suggested that the [geometry notebook](https://github.com/CUQI-DTU/CUQI-Book/blob/main/chapter05/geometries_in_cuqipy.ipynb) is more on general information on geometries, instead of in the context of forward models. So, keeping everything in the existing notebook is probably a better idea. With that being said, how much about geometries should we cover during the training is still a question not decided yet and I will create a separate issue on this https://github.com/CUQI-DTU/CUQIpy-admin/issues/17

**Comment by jakobsj** [comment]
@chaozg can you add DoD here please?

**Comment by chaozg** [comment]
Hi @jakobsj , could you help review the DoDs here?

**Comment by jakobsj** [comment]
@chaozg I am unsure on the last item with the comment inserted - is there a decision not to modify the notebook to reduce the amount of geometry? Is there a plan on which parts to cover/skip in the training?

**Comment by chaozg** [comment]
Hi @jakobsj I just updated Notes a bit and created an issue to track this issue
